# Generated by Django 4.0.5 on 2023-08-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='current_ctc',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='expected_ctc',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
