# Generated by Django 4.0.5 on 2023-08-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_applicant_current_ctc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='current_ctc',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='expected_ctc',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
    ]
